import { ArticlesSuccesResponse } from "../types/responses.types";

export const data: ArticlesSuccesResponse = {
  articles: [
    {
      source: { id: "google-news", name: "Google News" },
      author: "WP Wiadomości",
      title:
        "Pobite niemowlę w Tomaszowie Mazowieckim. Rodzice z zarzutami - WP Wiadomości",
      description: null,
      url: "https://news.google.com/rss/articles/CBMib2h0dHBzOi8vd2lhZG9tb3NjaS53cC5wbC9wb2JpdGUtbmllbW93bGUtdy10b21hc3pvd2llLW1hem93aWVja2ltLWR6aWVja28tdHJhZmlsby1kby1zenBpdGFsYS02ODk4NTk0NDgwMDc3NzI4YdIBdWh0dHBzOi8vd2lhZG9tb3NjaS53cC5wbC9wb2JpdGUtbmllbW93bGUtdy10b21hc3pvd2llLW1hem93aWVja2ltLWR6aWVja28tdHJhZmlsby1kby1zenBpdGFsYS02ODk4NTk0NDgwMDc3NzI4YT9hbXA9MQ?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T10:22:27Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Interia Wydarzenia",
      title:
        "Paweł Siennicki podał się do dymisji. Miał szantażować i grozić - Interia Wydarzenia",
      description: null,
      url: "https://news.google.com/rss/articles/CBMicGh0dHBzOi8vd3lkYXJ6ZW5pYS5pbnRlcmlhLnBsL2tyYWovbmV3cy1wYXdlbC1zaWVubmlja2ktcG9kYWwtc2llLWRvLWR5bWlzamktbWlhbC1zemFudGF6b3dhYy1pLWdyb3osbklkLDY3ODExODHSAXNodHRwczovL3d5ZGFyemVuaWEuaW50ZXJpYS5wbC9rcmFqL25ld3NhbXAtcGF3ZWwtc2llbm5pY2tpLXBvZGFsLXNpZS1kby1keW1pc2ppLW1pYWwtc3phbnRhem93YWMtaS1ncm96LG5JZCw2NzgxMTgx?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T10:08:49Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "WP.pl",
      title: "Wiedziała, że jest gejem. Po ślubie doczekali się córki - WP.pl",
      description: null,
      url: "https://news.google.com/rss/articles/CBMiXWh0dHBzOi8va29iaWV0YS53cC5wbC93aWVkemlhbGEtemUtamVzdC1nZWplbS1wby1zbHViaWUtZG9jemVrYWxpLXNpZS1jb3JraS02ODk4NTc2MTQzMjUyMzg0YdIBAA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T09:34:54Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "polsatnews.pl",
      title:
        "Rakieta pod Bydgoszczą. Banaś w Polsat News: NIK wszczęła kontrolę w Ministerstwie Obrony Narodowej - polsatnews.pl",
      description: null,
      url: "https://news.google.com/rss/articles/CBMikQFodHRwczovL3d3dy5wb2xzYXRuZXdzLnBsL3dpYWRvbW9zYy8yMDIzLTA1LTE2L3Jha2lldGEtcG9kLWJ5ZGdvc3pjemEtYmFuYXMtdy1wb2xzYXQtbmV3cy1uaWstd3N6Y3plbGEta29udHJvbGUtdy1taW5pc3RlcnN0d2llLW9icm9ueS1uYXJvZG93ZWov0gGVAWh0dHBzOi8vd3d3LnBvbHNhdG5ld3MucGwvd2lhZG9tb3NjLWFtcC8yMDIzLTA1LTE2L3Jha2lldGEtcG9kLWJ5ZGdvc3pjemEtYmFuYXMtdy1wb2xzYXQtbmV3cy1uaWstd3N6Y3plbGEta29udHJvbGUtdy1taW5pc3RlcnN0d2llLW9icm9ueS1uYXJvZG93ZWov?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T09:27:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Eurosport",
      title:
        "Iga Świątek - Donna Vekić: mecz przełożony z powodu deszczu - tenis - WTA 1000 Rzym - Eurosport",
      description: null,
      url: "https://news.google.com/rss/articles/CBMikgFodHRwczovL2V1cm9zcG9ydC50dm4yNC5wbC90ZW5pcy93dGEtcnp5bS8yMDIzL2lnYS1zd2lhdGVrLWRvbm5hLXZla2ljLW1lY3otcHJ6ZWxvem9ueS16LXBvd29kdS1kZXN6Y3p1LXRlbmlzLXd0YS0xMDAwLXJ6eW1fc3RvOTYwODI5My9zdG9yeS5zaHRtbNIBlgFodHRwczovL2V1cm9zcG9ydC50dm4yNC5wbC90ZW5pcy93dGEtcnp5bS8yMDIzL2lnYS1zd2lhdGVrLWRvbm5hLXZla2ljLW1lY3otcHJ6ZWxvem9ueS16LXBvd29kdS1kZXN6Y3p1LXRlbmlzLXd0YS0xMDAwLXJ6eW1fc3RvOTYwODI5My9zdG9yeS1hbXAuc2h0bWw?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T09:00:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "wiadomosci.gazeta.pl",
      title:
        'Kaczyński w niedzielę ani nie "posprzątał", ani nie "pozamiatał", ani nie "zaorał" [KOMENTARZ] - wiadomosci.gazeta.pl',
      description: null,
      url: "https://news.google.com/rss/articles/CBMiggFodHRwczovL3dpYWRvbW9zY2kuZ2F6ZXRhLnBsL3dpYWRvbW9zY2kvNywxMTQ4ODQsMjk3NjI3MzYsODAwLXBsdXMtdG8tbmFwcmF3ZGUtdGFraS1nYW1lLWNoYW5nZXIta2Fjenluc2tpLWFuaS1uaWUtcG96YW1pYXRhbC5odG1s0gGBAWh0dHBzOi8vd2lhZG9tb3NjaS5nYXpldGEucGwvd2lhZG9tb3NjaS83LDExNDg4NCwyOTc2MjczNiw4MDAtcGx1cy10by1uYXByYXdkZS10YWtpLWdhbWUtY2hhbmdlci1rYWN6eW5za2ktYW5pLW5pZS1wb3phbWlhdGFsLmFtcA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T08:28:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Onet",
      title:
        "Wulgaryzm na antenie TVN24. Prowadzący obraził Piotra Jaconia - Onet",
      description: null,
      url: "https://news.google.com/rss/articles/CBMigQFodHRwczovL3d3dy5vbmV0LnBsL2t1bHR1cmEvb25ldGt1bHR1cmEvcHJvd2FkemFjeS1zcHl0YWwtby1wbGVjLXBpb3RyYS1qYWNvbmlhLW9zdHJlLXNsb3dhLXctc3prb2xlLWtvbnRha3Rvd3ltLzl4a2xlc2YsNjgxYzFkZmHSAQA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T08:24:56Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "lublin112.pl",
      title:
        "Pokłóciła się z byłym mężem. Chwyciła za paliwo z kosiarki, po chwili płonęły budynki gospodarcze (zdjęcia) : Lublin112.pl – Wiadomości z Lublina i regionu. Ważne informacje z kraju - lublin112.pl",
      description: null,
      url: "https://news.google.com/rss/articles/CBMigQFodHRwczovL3d3dy5sdWJsaW4xMTIucGwvcG9rbG9jaWxhLXNpZS16LWJ5bHltLW1lemVtLWNod3ljaWxhLXphLXBhbGl3by16LWtvc2lhcmtpLXBvLWNod2lsaS1wbG9uZWx5LWJ1ZHlua2ktZ29zcG9kYXJjemUtemRqZWNpYS_SAQA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T08:05:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Gazeta Wyborcza",
      title:
        "To wam mogło umknąć: Kaczyński oprócz 800 plus obiecał koniec wolnych mediów - Gazeta Wyborcza",
      description: null,
      url: "https://news.google.com/rss/articles/CBMiZmh0dHBzOi8vd3lib3JjemEucGwvNyw3NTM5OCwyOTc2MDU0Myx0by13YW0tbW9nbG8tdW1rbmFjLWthY3p5bnNraS1vcHJvY3otODAwLXBsdXMtb2JpZWNhbC1rb25pZWMuaHRtbNIBAA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T08:03:35Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "BusinessInsider",
      title:
        "Hamowanie polskiej gospodarki. Spadek PKB w pierwszym kwartale - BusinessInsider",
      description: null,
      url: "https://news.google.com/rss/articles/CBMib2h0dHBzOi8vYnVzaW5lc3NpbnNpZGVyLmNvbS5wbC9nb3Nwb2RhcmthL2hhbW93YW5pZS1wb2xza2llai1nb3Nwb2RhcmtpLXNwYWRlay1wa2Itdy1waWVyd3N6eW0ta3dhcnRhbGUvZTJ4dmdwZ9IBAA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T08:01:05Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "polsatnews.pl",
      title:
        "Ukraina: Prezes Sądu Najwyższego Ukrainy zatrzymany. Przyjmował łapówkę - polsatnews.pl",
      description: null,
      url: "https://news.google.com/rss/articles/CBMidWh0dHBzOi8vd3d3LnBvbHNhdG5ld3MucGwvd2lhZG9tb3NjLzIwMjMtMDUtMTYvdWtyYWluYS1wcmV6ZXMtc2FkdS1uYWp3eXpzemVnby11a3JhaW55LXphdHJ6eW1hbnktcHJ6eWptb3dhbC1sYXBvd2tlL9IBeWh0dHBzOi8vd3d3LnBvbHNhdG5ld3MucGwvd2lhZG9tb3NjLWFtcC8yMDIzLTA1LTE2L3VrcmFpbmEtcHJlemVzLXNhZHUtbmFqd3l6c3plZ28tdWtyYWlueS16YXRyenltYW55LXByenlqbW93YWwtbGFwb3drZS8?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T07:55:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Sport.pl",
      title:
        'Mocne słowa ws. pożegnania Błaszczykowskiego. Ostry sprzeciw. "Nie róbmy jaj" - Sport.pl',
      description: null,
      url: "https://news.google.com/rss/articles/CBMia2h0dHBzOi8vd3d3LnNwb3J0LnBsL3BpbGthLzcsNjUwMzcsMjk3NjM1MTMsbW9jbmUtc2xvd2Etd3MtcG96ZWduYW5pYS1ibGFzemN6eWtvd3NraWVnby1vc3RyeS1zcHJ6ZWNpdy5odG1s0gFqaHR0cHM6Ly93d3cuc3BvcnQucGwvcGlsa2EvNyw2NTAzNywyOTc2MzUxMyxtb2NuZS1zbG93YS13cy1wb3plZ25hbmlhLWJsYXN6Y3p5a293c2tpZWdvLW9zdHJ5LXNwcnplY2l3LmFtcA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T07:39:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Gazeta Wyborcza",
      title:
        'Maciej Stuhr: "Mój tata jest na OIOM-ie i niczym nie dojeżdża" - Gazeta Wyborcza',
      description: null,
      url: "https://news.google.com/rss/articles/CBMiZmh0dHBzOi8vd3lib3JjemEucGwvNywxMDE3MDcsMjk3NjM2ODgsbWFjaWVqLXN0dWhyLW1vai10YXRhLWplc3QtbmEtb2lvbS1pZS1pLW5pY3p5bS1uaWUtZG9qZXpkemEuaHRtbNIBAA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T07:33:04Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "TVP Info",
      title:
        "Wygląda jak figura woskowa i ledwo mówi. Nowe nagranie z Łukaszenką - TVP Info",
      description: null,
      url: "https://news.google.com/rss/articles/CBMiX2h0dHBzOi8vd3d3LnR2cC5pbmZvLzY5ODczNzEzL2x1a2FzemVua2EtbGVkd28tbW93aS1pLWR6aXduaWUtd3lnbGFkYS1ub3dlLW5hZ3JhbmllLXotYmlhbG9ydXNp0gEA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T07:15:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "PPE.PL",
      title:
        "CD Projekt potwierdza duże zwolnienia u twórców Wiedźmin Sirius. Gra zaliczyła reboot - PPE.PL",
      description: null,
      url: "https://news.google.com/rss/articles/CBMieGh0dHBzOi8vd3d3LnBwZS5wbC9uZXdzLzMxOTI0Ni9jZC1wcm9qZWt0LXBvdHdpZXJkemEtZHV6ZS16d29sbmllbmlhLXUtdHdvcmNvdy13aWVkem1pbi1zaXJpdXMtZ3JhLXphbGljenlsYS1yZWJvb3QuaHRtbNIBAA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T07:05:53Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Interia Biznes",
      title:
        "Brytyjski gigant telekomunikacyjny Vodafone ogłasza masowe zwolnienia. Pracę ma stracić 11 tys. osób - Interia Biznes",
      description: null,
      url: "https://news.google.com/rss/articles/CBMicmh0dHBzOi8vYml6bmVzLmludGVyaWEucGwvZ29zcG9kYXJrYS9uZXdzLWJyeXR5anNraS1naWdhbnQtdGVsZWtvbXVuaWthY3lqbnktdm9kYWZvbmUtb2dsYXN6YS1tYXNvd2UteixuSWQsNjc4MTAyMtIBdWh0dHBzOi8vYml6bmVzLmludGVyaWEucGwvZ29zcG9kYXJrYS9uZXdzYW1wLWJyeXR5anNraS1naWdhbnQtdGVsZWtvbXVuaWthY3lqbnktdm9kYWZvbmUtb2dsYXN6YS1tYXNvd2UteixuSWQsNjc4MTAyMg?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T07:01:22Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Sportowefakty",
      title:
        "Żużel. Przebudzenie mocy Jarosława Hampela. Beniaminek sprawdził się na tle mistrzów Polski - Sportowefakty",
      description: null,
      url: "https://news.google.com/rss/articles/CBMiemh0dHBzOi8vc3BvcnRvd2VmYWt0eS53cC5wbC96dXplbC8xMDYwNDM0L3p1emVsLXByemVidWR6ZW5pZS1tb2N5LWphcm9zbGF3YS1oYW1wZWxhLWJlbmlhbWluZWstc3ByYXdkemlsLXNpZS1uYS10bGUtbWlzdHJ60gF-aHR0cHM6Ly9zcG9ydG93ZWZha3R5LndwLnBsL2FtcC96dXplbC8xMDYwNDM0L3p1emVsLXByemVidWR6ZW5pZS1tb2N5LWphcm9zbGF3YS1oYW1wZWxhLWJlbmlhbWluZWstc3ByYXdkemlsLXNpZS1uYS10bGUtbWlzdHJ6?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T06:52:41Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "gry-online.pl",
      title:
        "Jak pozornie niewinna gra okrutnie mnie przeraziła. Ten horror ma moc - gry-online.pl",
      description: null,
      url: "https://news.google.com/rss/articles/CBMiZGh0dHBzOi8vd3d3LmdyeS1vbmxpbmUucGwvbmV3c3Jvb20vYnJhbWJsZS10aGUtbW91bnRhaW4ta2luZy1tYS1tb2Mtb2tydXRuaWUtbW5pZS1wcnplcmF6aWxvL3oxMjUwMzfSATBodHRwczovL3d3dy5ncnktb25saW5lLnBsL1MwMTMtYW1wLmFzcD9JRD0xNTE2MDc?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T06:25:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "TVN24",
      title:
        "Szef Grupy Wagnera Jewgienij Prigożyn miał negocjować z Ukraińcami przejęcie Bachmutu. Analiza ISW - TVN24",
      description: null,
      url: "https://news.google.com/rss/articles/CBMigAFodHRwczovL3R2bjI0LnBsL3N3aWF0L3N6ZWYtZ3J1cHktd2FnbmVyYS1qZXdnaWVuaWotcHJpZ296eW4tbWlhbC1uZWdvY2pvd2FjLXotdWtyYWluY2FtaS1wcnplamVjaWUtYmFjaG11dHUtYW5hbGl6YS1pc3ctNzEyNzY1MtIBAA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T06:22:03Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "GeekWeek",
      title:
        "Kolejne przełomowe odkrycie Webba. NASA nie potrafi rozwiązać tej zagadki - GeekWeek",
      description: null,
      url: "https://news.google.com/rss/articles/CBMib2h0dHBzOi8vZ2Vla3dlZWsuaW50ZXJpYS5wbC9uYXVrYS9uZXdzLWtvbGVqbmUtcHJ6ZWxvbW93ZS1vZGtyeWNpZS13ZWJiYS1uYXNhLW5pZS1wb3RyYWZpLXJvendpYXphYyxuSWQsNjc4MDk4N9IBcmh0dHBzOi8vZ2Vla3dlZWsuaW50ZXJpYS5wbC9uYXVrYS9uZXdzYW1wLWtvbGVqbmUtcHJ6ZWxvbW93ZS1vZGtyeWNpZS13ZWJiYS1uYXNhLW5pZS1wb3RyYWZpLXJvendpYXphYyxuSWQsNjc4MDk4Nw?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T06:20:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "wiadomosci.gazeta.pl",
      title:
        'Rosyjskie drony niszczą obronę powietrzną Kijowa. Nocny atak "wyjątkowy w swojej gęstości" - wiadomosci.gazeta.pl',
      description: null,
      url: "https://news.google.com/rss/articles/CBMiemh0dHBzOi8vd2lhZG9tb3NjaS5nYXpldGEucGwvd2lhZG9tb3NjaS83LDExNDg4MSwyOTc2MzQwMixyb3N5anNraWUtZHJvbnktbmlzemN6YS1vYnJvbmUtcG93aWV0cnpuYS1raWpvd2Etbm9jbnktYXRhay5odG1s0gF5aHR0cHM6Ly93aWFkb21vc2NpLmdhemV0YS5wbC93aWFkb21vc2NpLzcsMTE0ODgxLDI5NzYzNDAyLHJvc3lqc2tpZS1kcm9ueS1uaXN6Y3phLW9icm9uZS1wb3dpZXRyem5hLWtpam93YS1ub2NueS1hdGFrLmFtcA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T05:25:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Bankier.pl",
      title:
        "Grupa Azoty szacuje stratę ponad pół miliarda złotych w I kw. - Bankier.pl",
      description: null,
      url: "https://news.google.com/rss/articles/CBMiY2h0dHBzOi8vd3d3LmJhbmtpZXIucGwvd2lhZG9tb3NjL0dydXBhLUF6b3R5LXN6YWN1amUtRUJJVERFLXctSS1rdy1uYS1taW51cy00MDEtbWxuLXpsLTg1NDA5NzUuaHRtbNIBYmh0dHBzOi8vd3d3LmJhbmtpZXIucGwvYW1wL3dpYWRvbW9zYy9HcnVwYS1Bem90eS1zemFjdWplLUVCSVRERS13LUkta3ctbmEtbWludXMtNDAxLW1sbi16bC04NTQwOTc1?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T05:08:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Dziennik",
      title:
        "HIMARS-y w Polsce. Gigantomania bez uzasadnienia [OPINIA] - Dziennik",
      description: null,
      url: "https://news.google.com/rss/articles/CBMiUmh0dHBzOi8vZ29zcG9kYXJrYS5kemllbm5pay5wbC9uZXdzL2FydHlrdWx5Lzg3MTYwMDcsaGltYXJzLXV6YnJvamVuaWUtcG9sc2thLmh0bWzSAVZodHRwczovL2dvc3BvZGFya2EuZHppZW5uaWsucGwvbmV3cy9hcnR5a3VseS84NzE2MDA3LGhpbWFycy11emJyb2plbmllLXBvbHNrYS5odG1sLmFtcA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T04:40:40Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Defence24.pl",
      title:
        "446. dzień inwazji Federacji Rosyjskiej przeciwko Ukrainie [Podsumowanie] - Defence24.pl",
      description: null,
      url: "https://news.google.com/rss/articles/CBMiiAFodHRwczovL2RlZmVuY2UyNC5wbC93b2puYS1uYS11a3JhaW5pZS1yYXBvcnQtc3BlY2phbG55LWRlZmVuY2UyNC80NDYtZHppZW4taW53YXpqaS1mZWRlcmFjamktcm9zeWpza2llai1wcnplY2l3a28tdWtyYWluaWUtcG9kc3Vtb3dhbmll0gEA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T04:39:03Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "next.gazeta.pl",
      title:
        "Kursy walut 16.05. Złoty wciąż mocny. Euro bardzo słabe [kurs dolara, funta, euro, franka] - next.gazeta.pl",
      description: null,
      url: "https://news.google.com/rss/articles/CBMibWh0dHBzOi8vbmV4dC5nYXpldGEucGwvbmV4dC83LDE1MTAwMywyOTc2MzM5NyxrdXJzeS13YWx1dC0xNi0wNS16bG90eS13Y2lhei1tb2NueS1ldXJvLWJhcmR6by1zbGFiZS1rdXJzLmh0bWzSAWxodHRwczovL25leHQuZ2F6ZXRhLnBsL25leHQvNywxNTEwMDMsMjk3NjMzOTcsa3Vyc3ktd2FsdXQtMTYtMDUtemxvdHktd2NpYXotbW9jbnktZXVyby1iYXJkem8tc2xhYmUta3Vycy5hbXA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T04:30:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "WP Wiadomości",
      title: "PiS traci władzę. Mamy najnowszy sondaż - WP Wiadomości",
      description: null,
      url: "https://news.google.com/rss/articles/CBMiZmh0dHBzOi8vd2lhZG9tb3NjaS53cC5wbC9uaWUtcG9tb3plLW5hd2V0LWtvbmZlZGVyYWNqYS1zb25kYXotcG90d2llcmR6YS1rbG9wb3R5LXBpcy02ODk4MjM3NTkxNjIwMzUyYdIBbGh0dHBzOi8vd2lhZG9tb3NjaS53cC5wbC9uaWUtcG9tb3plLW5hd2V0LWtvbmZlZGVyYWNqYS1zb25kYXotcG90d2llcmR6YS1rbG9wb3R5LXBpcy02ODk4MjM3NTkxNjIwMzUyYT9hbXA9MQ?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T04:09:54Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Gazeta",
      title:
        "Quiz - Czas na 5 ekstremalnie trudnych pytań. Nowy quiz akademicki da ci popalić! - Gazeta.pl - Gazeta",
      description: null,
      url: "https://news.google.com/rss/articles/CBMicWh0dHBzOi8va3VsdHVyYS5nYXpldGEucGwva3VsdHVyYS8xMywxNDM0OTksMTcxOTEsY3phcy1uYS01LWVrc3RyZW1hbG5pZS10cnVkbnljaC1weXRhbi1ub3d5LXF1aXotYWthZGVtaWNraS5odG1s0gEA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-16T04:00:12Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Polski Portal Hokejowy - Hokej.Net",
      title:
        "Mistrzostwa Świata: Nordycki klasyk jak Eurowizja, historyczna porażka Czechów [WIDEO] | Hokej.Net - Polski Portal Hokejowy - Hokej.Net",
      description: null,
      url: "https://news.google.com/rss/articles/CBMibGh0dHBzOi8vaG9rZWoubmV0L2FydHlrdWwvbWlzdHJ6b3N0d2Etc3dpYXRhLW5vcmR5Y2tpLWtsYXN5ay1qYWstZXVyb3dpemphLWhpc3Rvcnljem5hLXBvcmF6a2EtY3plY2hvdy13aWRlb9IBAA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-15T19:56:00Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Plejada.pl",
      title:
        "Cezary Pazura opowiedział o partnerze swojej córki. Wkrótce będzie teściem? - Plejada.pl",
      description: null,
      url: "https://news.google.com/rss/articles/CBMiamh0dHBzOi8vcGxlamFkYS5wbC9uZXdzeS9jZXphcnktcGF6dXJhLW9wb3dpZWR6aWFsLW8tcGFydG5lcnplLXN3b2plai1jb3JraS13a3JvdGNlLWJlZHppZS10ZXNjaWVtL2pmODB0a27SAQA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-15T16:32:50Z",
      content: null,
    },
    {
      source: { id: "google-news", name: "Google News" },
      author: "Fakt.pl",
      title:
        '"Bild" napisał okrutny tekst na temat występu Blanki. Przykre słowa - Fakt.pl',
      description: null,
      url: "https://news.google.com/rss/articles/CBMiX2h0dHBzOi8vbHVkemllLmZha3QucGwvYmlsZC1uYXBpc2FsLW9rcnV0bnktdGVrc3QtbmEtdGVtYXQtd3lzdGVwdS1ibGFua2ktcHJ6eWtyZS1zbG93YS9la3lxeWt30gEA?oc=5",
      urlToImage: null,
      publishedAt: "2023-05-15T11:51:00Z",
      content: null,
    },
  ],
  status: "ok",
  totalResults: 30,
};
